# Generated by Django 4.2.29 on 2026-03-11 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePotencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, help_text='Ej: V-12345678, E-87654321', max_length=15, unique=True, verbose_name='Cédula de Identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('direccion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Ej: +58 412-1234567', max_length=20, verbose_name='Teléfono')),
                ('posee_internet', models.BooleanField(default=False, help_text='Marcar si ya tiene servicio de internet', verbose_name='¿Posee internet?')),
                ('interesado', models.CharField(choices=[('SI', 'Sí'), ('TAL_VEZ', 'Tal vez'), ('NO', 'No')], default='TAL_VEZ', max_length=10, verbose_name='Nivel de interés')),
                ('observacion', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente', max_length=500, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateField(default=datetime.date.today, help_text='Fecha en que se registró el cliente', verbose_name='Fecha de registro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación en sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que registró este cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_potenciales_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente Potencial',
                'verbose_name_plural': 'Clientes Potenciales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
