# Generated by Django 4.2.29 on 2026-03-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_perfilusuario_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ubicación de Usuario',
                'verbose_name_plural': 'Ubicaciones de Usuarios',
                'indexes': [models.Index(fields=['ultima_actualizacion'], name='myapp_ubica_ultima__76c93b_idx')],
            },
        ),
    ]
