# Generated by Django 4.2.29 on 2026-03-14 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_ubicacionusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Modalidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Modalidad de Equipo',
                'verbose_name_plural': 'Modalidades de Equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Plan')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Red')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Vivienda')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Vivienda',
                'verbose_name_plural': 'Tipos de Vivienda',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.PositiveIntegerField(verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono Principal')),
                ('otro_telefono', models.CharField(blank=True, help_text='Teléfono adicional de contacto', max_length=20, null=True, verbose_name='Otro Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion_detallada', models.TextField(help_text='Calle, avenida, urbanización, casa/edificio, piso, apartamento', max_length=500, verbose_name='Dirección Detallada')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('simple_plus', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text='¿El cliente tiene Simple Plus?', max_length=2, verbose_name='Simple Plus')),
                ('punto_referencia', models.CharField(help_text='Referencia para encontrar la ubicación', max_length=255, verbose_name='Punto de Referencia')),
                ('numero_casa', models.CharField(help_text='Número de la casa, edificio, apartamento', max_length=50, verbose_name='Número de Casa/Edificio')),
                ('numero_pago_movil', models.CharField(help_text='Número de teléfono donde se realizó el pago', max_length=20, verbose_name='Número de Pago Móvil')),
                ('foto_pago', models.ImageField(help_text='Captura de pantalla o foto del comprobante de pago', upload_to='pagos/', verbose_name='Foto del Pago')),
                ('ods', models.CharField(blank=True, help_text='Orden de Servicio (solo administrador)', max_length=50, null=True, verbose_name='ODS')),
                ('customer_id', models.CharField(blank=True, help_text='ID del cliente en el sistema (solo administrador)', max_length=50, null=True, verbose_name='Customer ID')),
                ('atr', models.CharField(blank=True, help_text='ATR', max_length=50, null=True, verbose_name='ATR')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('NO_COMPLETADO', 'No Completado')], default='EN_PROCESO', max_length=15, verbose_name='Estado del Contrato')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente_potencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='myapp.clientepotencial', verbose_name='Cliente Potencial')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modalidad_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='myapp.modalidadequipo', verbose_name='Modalidad del Equipo')),
                ('plan_contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='myapp.plan', verbose_name='Plan a Contratar')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='myapp.red', verbose_name='Red')),
                ('tipo_vivienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='myapp.tipovivienda', verbose_name='Tipo de Vivienda')),
            ],
            options={
                'verbose_name': 'Contrato de Cliente',
                'verbose_name_plural': 'Contratos de Clientes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='myapp_contr_estado_6a3b67_idx'), models.Index(fields=['fecha_creacion'], name='myapp_contr_fecha_c_40974f_idx')],
            },
        ),
    ]
