# Generated by Django 4.2.29 on 2026-03-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_modalidadequipo_plan_red_tipovivienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='contratocliente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='contratocliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='contratocliente',
            name='telefono_principal',
        ),
    ]
