# Generated by Django 4.2.29 on 2026-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_contratocliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
