# Generated by Django 4.2.29 on 2026-03-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_contratocliente_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocliente',
            name='atr',
            field=models.CharField(blank=True, default='*VTC Conexiones', help_text='ATR', max_length=50, null=True, verbose_name='ATR'),
        ),
        migrations.AddIndex(
            model_name='contratocliente',
            index=models.Index(fields=['correo_electronico'], name='myapp_contr_correo__77c56a_idx'),
        ),
    ]
