# Generated by Django 4.2.29 on 2026-03-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_contratocliente_atr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocliente',
            name='foto_pago',
            field=models.ImageField(blank=True, help_text='Captura de pantalla o foto del comprobante de pago', null=True, upload_to='pagos/', verbose_name='Foto del Pago'),
        ),
        migrations.AlterField(
            model_name='contratocliente',
            name='numero_pago_movil',
            field=models.CharField(blank=True, help_text='Número de teléfono donde se realizó el pago', max_length=20, null=True, verbose_name='Número de Pago Móvil'),
        ),
    ]
