# Generated by Django 4.2.29 on 2026-03-18 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_alter_contratocliente_foto_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Cuadrilla')),
                ('codigo', models.CharField(help_text='Ej: C001, INST-001', max_length=20, unique=True, verbose_name='Código de Cuadrilla')),
                ('capacidad_maxima', models.PositiveIntegerField(default=2, help_text='Número máximo de instalaciones por día', verbose_name='Capacidad Máxima')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('DESCANSO', 'En Descanso'), ('INACTIVO', 'Inactivo')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado de la Cuadrilla')),
                ('ubicacion_actual_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud actual')),
                ('ubicacion_actual_lng', models.FloatField(blank=True, null=True, verbose_name='Longitud actual')),
                ('ultima_actualizacion_ubicacion', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('instaladores', models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'rol': 'INSTALADOR'}, related_name='cuadrillas', to='myapp.perfilusuario', verbose_name='Instaladores')),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='myapp_cuadr_estado_718e35_idx'), models.Index(fields=['activo'], name='myapp_cuadr_activo_3f023b_idx'), models.Index(fields=['codigo'], name='myapp_cuadr_codigo_5aeec5_idx')],
            },
        ),
    ]
