# Generated by Django 4.2.29 on 2026-03-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cuadrilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadrilla',
            name='ubicacion_actual_lat',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='ubicacion_actual_lng',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='ultima_actualizacion_ubicacion',
        ),
    ]
