# Generated by Django 4.2.29 on 2026-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_cuadrilla_ubicacion_actual_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
