# Generated by Django 4.2.29 on 2026-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_perfilusuario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrilla',
            name='instaladores',
            field=models.ManyToManyField(blank=True, related_name='cuadrillas', to='myapp.perfilusuario', verbose_name='Instaladores'),
        ),
    ]
