# Generated by Django 4.2.29 on 2026-03-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_cuadrilla_instaladores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadrilla',
            name='capacidad_maxima',
        ),
    ]
