# Generated by Django 4.2.29 on 2026-03-19 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_remove_cuadrilla_capacidad_maxima'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.contratocliente', verbose_name='Contrato')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.cuadrilla', verbose_name='Cuadrilla')),
            ],
            options={
                'verbose_name': 'Asignación de Contrato',
                'verbose_name_plural': 'Asignaciones de Contratos',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['activo'], name='myapp_asign_activo_54ca82_idx'), models.Index(fields=['fecha_asignacion'], name='myapp_asign_fecha_a_24dfef_idx')],
            },
        ),
    ]
