# Generated by Django 4.2.29 on 2026-03-20 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_asignacioncontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloModem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Modelo del Modem')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Modelo de Módem',
                'verbose_name_plural': 'Modelos de Módem',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_servicio', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Orden de Servicio')),
                ('feeder', models.CharField(blank=True, max_length=50, null=True, verbose_name='FEEDER')),
                ('caja', models.CharField(blank=True, max_length=50, null=True, verbose_name='CAJA')),
                ('puerto_utilizado', models.CharField(blank=True, max_length=10, null=True, verbose_name='PUERTO UTILIZADO')),
                ('ubicacion_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('ubicacion_lng', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('sn_modem', models.CharField(max_length=50, verbose_name='Serial del Módem')),
                ('mac_modem', models.CharField(max_length=50, verbose_name='MAC del Módem')),
                ('inicio_fibra', models.PositiveIntegerField(help_text='Medición inicial de fibra', verbose_name='INICIO')),
                ('final_fibra', models.PositiveIntegerField(help_text='Medición final de fibra', verbose_name='FINAL')),
                ('conectores', models.PositiveIntegerField(default=0, verbose_name='CONECTORES')),
                ('rosetas', models.PositiveIntegerField(default=0, verbose_name='ROSETAS')),
                ('patch_cord', models.PositiveIntegerField(default=0, verbose_name='PACH CORD')),
                ('tensores', models.PositiveIntegerField(default=0, verbose_name='TENSORES')),
                ('conectores_malos', models.PositiveIntegerField(default=0, verbose_name='CONECTORES MALOS')),
                ('observacion', models.TextField(blank=True, max_length=500, null=True, verbose_name='OBSERVACIÓN')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_instalacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instalacion', to='myapp.asignacioncontrato', verbose_name='Asignación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizada por')),
                ('modelo_modem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='myapp.modelomodem', verbose_name='Modelo del Módem')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['orden_servicio'], name='myapp_insta_orden_s_041a1f_idx'), models.Index(fields=['completada'], name='myapp_insta_complet_46f49a_idx'), models.Index(fields=['fecha_instalacion'], name='myapp_insta_fecha_i_c7921e_idx')],
            },
        ),
    ]
