# Generated by Django 4.2.29 on 2026-03-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_modelomodem_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='conectores',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CONECTORES'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='conectores_malos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CONECTORES MALOS'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='final_fibra',
            field=models.PositiveIntegerField(blank=True, help_text='Medición final de fibra', null=True, verbose_name='FINAL'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='inicio_fibra',
            field=models.PositiveIntegerField(blank=True, help_text='Medición inicial de fibra', null=True, verbose_name='INICIO'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='rosetas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ROSETAS'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='tensores',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='TENSORES'),
        ),
    ]
