# Generated by Django 4.2.29 on 2026-03-20 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_instalacion_conectores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='mac_modem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC del Módem'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='modelo_modem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='myapp.modelomodem', verbose_name='Modelo del Módem'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='sn_modem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial del Módem'),
        ),
    ]
