# Generated by Django 4.2.29 on 2026-03-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_instalacion_mac_modem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='orden_servicio',
            field=models.CharField(editable=False, max_length=10, verbose_name='Orden de Servicio'),
        ),
    ]
