# Generated by Django 4.2.29 on 2026-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_instalacion_orden_servicio'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instalacion',
            name='myapp_insta_orden_s_041a1f_idx',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='orden_servicio',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='ubicacion_lat',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='ubicacion_lng',
        ),
        migrations.AddField(
            model_name='instalacion',
            name='fotos',
            field=models.JSONField(default=list, help_text='Lista de URLs de las fotos subidas', verbose_name='Fotos de la instalación'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Coordenada de la ubicación del cliente', null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Coordenada de la ubicación del cliente', null=True, verbose_name='Longitud'),
        ),
    ]
