# Generated by Django 4.2.29 on 2026-03-28 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0020_remove_instalacion_myapp_insta_orden_s_041a1f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDirecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.CharField(help_text='Número único de orden de venta', max_length=50, unique=True, verbose_name='Número de Orden')),
                ('cedula', models.CharField(help_text='Cédula del cliente', max_length=15, verbose_name='Cédula')),
                ('customer_id', models.CharField(blank=True, help_text='ID del cliente en el sistema', max_length=50, null=True, verbose_name='Customer ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('NO_COMPLETADO', 'No Completado')], default='EN_PROCESO', max_length=15, verbose_name='Estado de la Venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación en sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('observacion', models.TextField(blank=True, help_text='Notas adicionales sobre la venta', max_length=500, null=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_directas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_directas', to='myapp.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Venta Directa',
                'verbose_name_plural': 'Ventas Directas',
                'ordering': ['-fecha', '-fecha_creacion'],
                'indexes': [models.Index(fields=['nro_orden'], name='myapp_venta_nro_ord_97c2ef_idx'), models.Index(fields=['cedula'], name='myapp_venta_cedula_ae3339_idx'), models.Index(fields=['fecha'], name='myapp_venta_fecha_33cff6_idx'), models.Index(fields=['estado'], name='myapp_venta_estado_7b22c0_idx')],
            },
        ),
    ]
