# Generated by Django 4.2.29 on 2026-03-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_ventadirecta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncontrato',
            name='venta_directa',
            field=models.ForeignKey(blank=True, help_text='Venta directa de la torre de control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.ventadirecta', verbose_name='Venta Directa'),
        ),
        migrations.AddIndex(
            model_name='asignacioncontrato',
            index=models.Index(fields=['contrato'], name='myapp_asign_contrat_326727_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncontrato',
            index=models.Index(fields=['venta_directa'], name='myapp_asign_venta_d_cd7439_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacioncontrato',
            constraint=models.CheckConstraint(check=models.Q(('contrato__isnull', False), ('venta_directa__isnull', False), _connector='OR'), name='asignacion_tiene_origen'),
        ),
    ]
