# Generated by Django 4.2.29 on 2026-03-28 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_asignacioncontrato_venta_directa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncontrato',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.contratocliente', verbose_name='Contrato'),
        ),
    ]
