# Generated by Django 4.2.29 on 2026-03-28 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_asignacioncontrato_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncontrato',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato generado por vendedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.contratocliente', verbose_name='Contrato de Vendedor'),
        ),
    ]
