# Generated by Django 4.2.29 on 2026-04-01 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0024_alter_asignacioncontrato_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='instaladores',
            field=models.ManyToManyField(blank=True, related_name='instalaciones', to=settings.AUTH_USER_MODEL, verbose_name='Instaladores que realizaron la instalación'),
        ),
    ]
