# Generated by Django 4.2.29 on 2026-04-01 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0025_instalacion_instaladores'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tasa de Cambio (USD a Bs)')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de vigencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NominaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Inicio de semana (viernes)')),
                ('semana_fin', models.DateField(verbose_name='Fin de semana (viernes siguiente)')),
                ('total_contratos', models.PositiveIntegerField(default=0, verbose_name='Total contratos completados en la semana')),
                ('rango', models.CharField(blank=True, choices=[('1-5', '1 a 5 contratos'), ('6-10', '6 a 10 contratos'), ('11+', '11 o más contratos')], max_length=10, null=True, verbose_name='Rango alcanzado')),
                ('comision_por_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión por contrato (USD)')),
                ('comision_total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total comisiones (USD)')),
                ('bono_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bono semanal (USD)')),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total a pagar (USD)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Nómina de Vendedor',
                'verbose_name_plural': 'Nóminas de Vendedores',
                'ordering': ['-semana_inicio', 'vendedor__username'],
                'unique_together': {('vendedor', 'semana_inicio')},
            },
        ),
    ]
