# Generated by Django 4.2.29 on 2026-04-01 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0026_tasacambio_nominavendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominavendedor',
            options={'ordering': ['-semana_inicio', 'vendedor__username'], 'verbose_name': 'Nómina Semanal', 'verbose_name_plural': 'Nóminas Semanales'},
        ),
        migrations.AddField(
            model_name='nominavendedor',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='nominavendedor',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='nominavendedor',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas_semanales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
