# Generated by Django 4.2.29 on 2026-04-01 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0027_alter_nominavendedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominavendedor',
            options={'ordering': ['-semana_inicio', 'vendedor__username'], 'verbose_name': 'Nómina de Vendedor', 'verbose_name_plural': 'Nóminas de Vendedores'},
        ),
        migrations.RemoveField(
            model_name='nominavendedor',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='nominavendedor',
            name='pagado',
        ),
        migrations.AlterField(
            model_name='nominavendedor',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
