# Generated by Django 4.2.29 on 2026-04-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0028_alter_nominavendedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MUDANZA', 'Mudanza'), ('RETIRO', 'Retiro'), ('RECABLEADO', 'Recableado')], db_index=True, max_length=20, verbose_name='Tipo de Soporte')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('INCOMPLETO', 'Incompleto'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado del Soporte')),
                ('fecha_hora_servicio', models.DateTimeField(help_text='Fecha y hora en que se realizó el servicio', verbose_name='Fecha y hora del servicio realizado')),
                ('falla_encontrada', models.TextField(help_text='Breve descripción de la falla encontrada', max_length=500, verbose_name='Falla encontrada')),
                ('solucion', models.TextField(help_text='Breve descripción de la solución aplicada', max_length=500, verbose_name='Solución de la misma')),
                ('inicio_fibra', models.PositiveIntegerField(blank=True, help_text='Medición inicial de fibra', null=True, verbose_name='INICIO')),
                ('final_fibra', models.PositiveIntegerField(blank=True, help_text='Medición final de fibra', null=True, verbose_name='FINAL')),
                ('conectores', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CONECTORES')),
                ('rosetas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ROSETAS')),
                ('patch_cord', models.PositiveIntegerField(default=0, verbose_name='PATCH CORD')),
                ('tensores', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='TENSORES')),
                ('conectores_malos', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CONECTORES MALOS')),
                ('pin_ubicacion_lat', models.FloatField(blank=True, help_text='Coordenada de latitud donde se realizó el soporte', null=True, verbose_name='Latitud del pin de ubicación')),
                ('pin_ubicacion_lng', models.FloatField(blank=True, help_text='Coordenada de longitud donde se realizó el soporte', null=True, verbose_name='Longitud del pin de ubicación')),
                ('puerto_nap_utilizado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Puerto en caja NAP utilizado')),
                ('caja_nap_utilizada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja NAP utilizada (Nomenclatura)')),
                ('fotos', models.JSONField(default=list, help_text='Lista de URLs de las fotos (equipos, material, falla, solución, speed test)', verbose_name='Soporte fotográfico')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes', to='myapp.cuadrilla', verbose_name='Cuadrilla que realizó el soporte')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='myapp.instalacion', verbose_name='Instalación relacionada')),
                ('instaladores', models.ManyToManyField(related_name='soportes_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Instaladores que realizaron el soporte')),
            ],
            options={
                'verbose_name': 'Soporte',
                'verbose_name_plural': 'Soportes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo'], name='myapp_sopor_tipo_f06822_idx'), models.Index(fields=['estado'], name='myapp_sopor_estado_c500fa_idx'), models.Index(fields=['fecha_hora_servicio'], name='myapp_sopor_fecha_h_bc2273_idx'), models.Index(fields=['instalacion'], name='myapp_sopor_instala_17891b_idx')],
            },
        ),
    ]
