# Generated by Django 4.2.29 on 2026-04-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='mac_modem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC del Módem'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='modelo_modem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soportes', to='myapp.modelomodem', verbose_name='Modelo del Módem'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='sn_modem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial del Módem'),
        ),
    ]
