# Generated by Django 4.2.29 on 2026-04-15 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0030_soporte_mac_modem_soporte_modelo_modem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del material')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', '➕ Entrada (Compra/Adición)'), ('SALIDA_CUADRILLA', '📦 Salida a cuadrilla'), ('DEVOLUCION', '🔄 Devolución de cuadrilla'), ('GASTO_INSTALACION', '🔧 Gasto en instalación'), ('GASTO_SOPORTE', '🛠️ Gasto en soporte'), ('AJUSTE', '📝 Ajuste manual')], max_length=30, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('observacion', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='myapp.cuadrilla', verbose_name='Cuadrilla relacionada')),
                ('instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='myapp.instalacion', verbose_name='Instalación relacionada')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='myapp.material', verbose_name='Material')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('soporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='myapp.soporte', verbose_name='Soporte relacionado')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='InventarioGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible')),
                ('cantidad_minima', models.PositiveIntegerField(default=5, verbose_name='Cantidad mínima de alerta')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_global', to='myapp.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Inventario Global',
                'verbose_name_plural': 'Inventario Global',
                'unique_together': {('material',)},
            },
        ),
        migrations.CreateModel(
            name='InventarioCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad en cuadrilla')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='myapp.cuadrilla', verbose_name='Cuadrilla')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_cuadrillas', to='myapp.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Inventario de Cuadrilla',
                'verbose_name_plural': 'Inventarios de Cuadrillas',
                'unique_together': {('cuadrilla', 'material')},
            },
        ),
    ]
