# Generated by Django 4.2.29 on 2026-04-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_material_movimientoinventario_inventarioglobal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='modelo_modem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='myapp.modelomodem', verbose_name='Modelo del Módem'),
        ),
    ]
