# Generated by Django 4.2.29 on 2026-04-15 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_soporte_modelo_modem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioglobal',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_global', to='myapp.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='myapp.material', verbose_name='Material'),
        ),
    ]
