# Generated by Django 4.2.29 on 2026-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_inventarioglobal_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='tirros',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Cantidad de tirros utilizados en la instalación', null=True, verbose_name='TIRROS'),
        ),
    ]
