# Generated by Django 4.2.29 on 2026-04-23 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0034_instalacion_tirros'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Asignación de Soporte',
                'verbose_name_plural': 'Asignaciones de Soporte',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_padre', models.CharField(db_index=True, help_text='Ej: SIMPLETV-06319623', max_length=50, verbose_name='Ticket Padre')),
                ('tipo_soporte', models.CharField(choices=[('MUDANZA', 'Mudanza'), ('RETIRO', 'Retiro'), ('RECABLEADO', 'Recableado'), ('SOPORTE', 'Soporte Técnico')], db_index=True, default='SOPORTE', max_length=20, verbose_name='Tipo de Soporte')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(db_index=True, max_length=15, verbose_name='Cédula')),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Customer ID')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Alternativo')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(help_text='Dirección completa del cliente (calle, avenida, urbanización, casa/edificio, referencia)', max_length=500, verbose_name='Dirección')),
                ('falla', models.CharField(help_text='Ej: Sin conexión a internet, Mudanza, Retiro de equipo, etc.', max_length=255, verbose_name='Falla o Solicitud')),
                ('descripcion_falla', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción detallada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado del Ticket')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del reporte')),
                ('fecha_requerida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora requerida para el servicio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación en sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AlterModelOptions(
            name='soporte',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Soporte Técnico', 'verbose_name_plural': 'Soportes Técnicos'},
        ),
        migrations.RemoveIndex(
            model_name='soporte',
            name='myapp_sopor_tipo_f06822_idx',
        ),
        migrations.RemoveIndex(
            model_name='soporte',
            name='myapp_sopor_estado_c500fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='soporte',
            name='myapp_sopor_fecha_h_bc2273_idx',
        ),
        migrations.RemoveIndex(
            model_name='soporte',
            name='myapp_sopor_instala_17891b_idx',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='instalacion',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='tipo',
        ),
        migrations.AddField(
            model_name='soporte',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización del servicio'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio del servicio'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='tirros',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Cantidad de tirros utilizados', null=True, verbose_name='TIRROS'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='tirros',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Cantidad de tirros utilizados en la instalación', null=True, verbose_name='TIRROS'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Adición)'), ('SALIDA_CUADRILLA', 'Salida a cuadrilla'), ('DEVOLUCION', 'Devolución de cuadrilla'), ('GASTO_INSTALACION', '🔧 Gasto en instalación'), ('GASTO_SOPORTE', 'Gasto en soporte'), ('AJUSTE', 'Ajuste manual')], max_length=30, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='caja_nap_utilizada',
            field=models.CharField(blank=True, help_text='Nomenclatura de la caja NAP', max_length=100, null=True, verbose_name='Caja NAP utilizada'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_tecnicos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_tecnicos', to='myapp.cuadrilla', verbose_name='Cuadrilla ejecutora'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('NO_COMPLETADO', 'No Completado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado de la ejecución'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='falla_encontrada',
            field=models.TextField(blank=True, help_text='Breve descripción de la falla encontrada', max_length=500, null=True, verbose_name='Falla encontrada'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='fecha_hora_servicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se realizó el servicio', null=True, verbose_name='Fecha y hora del servicio realizado'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='instaladores',
            field=models.ManyToManyField(related_name='soportes_tecnicos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Instaladores que realizaron el soporte'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='modelo_modem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soportes_tecnicos', to='myapp.modelomodem', verbose_name='Modelo del Módem'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='solucion',
            field=models.TextField(blank=True, help_text='Breve descripción de la solución aplicada', max_length=500, null=True, verbose_name='Solución aplicada'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='myapp.plan', verbose_name='Plan Contratado'),
        ),
        migrations.AddField(
            model_name='asignacionsoporte',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_soporte_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='asignacionsoporte',
            name='cuadrilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_soporte', to='myapp.cuadrilla', verbose_name='Cuadrilla asignada'),
        ),
        migrations.AddField(
            model_name='asignacionsoporte',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.ticket', verbose_name='Ticket de Soporte'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='asignacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soporte_ejecucion', to='myapp.asignacionsoporte', verbose_name='Asignación de Soporte'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_padre'], name='myapp_ticke_ticket__3028e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cedula'], name='myapp_ticke_cedula_f99b60_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='myapp_ticke_estado_e487b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tipo_soporte'], name='myapp_ticke_tipo_so_0e987e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['fecha_reporte'], name='myapp_ticke_fecha_r_4d41cc_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionsoporte',
            index=models.Index(fields=['activo'], name='myapp_asign_activo_a7f793_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionsoporte',
            index=models.Index(fields=['fecha_asignacion'], name='myapp_asign_fecha_a_93e6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionsoporte',
            index=models.Index(fields=['ticket'], name='myapp_asign_ticket__993f94_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionsoporte',
            index=models.Index(fields=['cuadrilla'], name='myapp_asign_cuadril_4470a7_idx'),
        ),
    ]
