# Generated by Django 4.2.29 on 2026-04-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_asignacionsoporte_ticket_alter_soporte_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='descripcion_falla',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='telefono_alternativo',
        ),
    ]
