# Generated by Django 4.2.29 on 2026-04-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_ticket_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='mac_modem_viejo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC del Módem'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='modem_viejo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial del Módem'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='sn_modem_viejo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial del Módem'),
        ),
    ]
