# Generated by Django 4.2.29 on 2026-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_soporte_mac_modem_viejo_soporte_modem_viejo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncontrato',
            name='trabajo_interno',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sc'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='mac_modem_viejo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC del Módem Viejo'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='modem_viejo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo del Módem viejo'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='sn_modem_viejo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial del Módem Viejo'),
        ),
    ]
