# Generated by Django 4.2.29 on 2026-05-12 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0039_contratocliente_fecha_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Banco')),
                ('codigo', models.CharField(help_text='Ej: 0102, 0134, etc.', max_length=10, unique=True, verbose_name='Código del Banco')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente Externo',
                'verbose_name_plural': 'Clientes Externos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetallePagoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(help_text='Número desde donde se realizó el Pago Móvil', max_length=20, verbose_name='Número de teléfono')),
                ('cedula_titular', models.CharField(help_text='Cédula de la persona que realizó el pago', max_length=15, verbose_name='Cédula del titular')),
                ('referencia', models.CharField(max_length=50, unique=True, verbose_name='Número de referencia')),
                ('banco_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_movil_emisor', to='myapp.banco', verbose_name='Banco emisor (desde donde pagas)')),
                ('banco_receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_movil_receptor', to='myapp.banco', verbose_name='Banco receptor (nuestro banco)')),
            ],
            options={
                'verbose_name': 'Detalle Pago Móvil',
                'verbose_name_plural': 'Detalles Pago Móvil',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_titular', models.CharField(help_text='Cédula de la persona que realizó la transferencia', max_length=15, verbose_name='Cédula del titular')),
                ('numero_cuenta_origen', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de cuenta origen')),
                ('referencia', models.CharField(max_length=50, unique=True, verbose_name='Número de referencia')),
                ('banco_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='myapp.banco', verbose_name='Banco de destino')),
                ('banco_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='myapp.banco', verbose_name='Banco de origen')),
            ],
            options={
                'verbose_name': 'Detalle Transferencia',
                'verbose_name_plural': 'Detalles Transferencia',
            },
        ),
        migrations.CreateModel(
            name='ReportePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('INTERNO', 'Cliente interno'), ('EXTERNO', 'Cliente externo')], max_length=10, verbose_name='Tipo de cliente')),
                ('medio_pago', models.CharField(choices=[('PAGO_MOVIL', 'Pago Móvil'), ('TRANSFERENCIA', 'Transferencia Bancaria')], max_length=20, verbose_name='Medio de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado (Bs)')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del pago')),
                ('comprobante', models.ImageField(upload_to='comprobantes_pagos/%Y/%m/', verbose_name='Comprobante de pago')),
                ('observacion_cliente', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones del cliente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de validación'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado'), ('APLICADO', 'Aplicado al contrato')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado del reporte')),
                ('rechazo_motivo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Motivo de rechazo')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del cliente')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navegador/Dispositivo')),
                ('cliente_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_pago', to='myapp.clienteexterno', verbose_name='Cliente externo (no está en sistema)')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_pago', to='myapp.contratocliente', verbose_name='Contrato asociado (cliente interno)')),
                ('detalle_pago_movil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporte_pago', to='myapp.detallepagomovil', verbose_name='Detalle Pago Móvil')),
                ('detalle_transferencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporte_pago', to='myapp.detalletransferencia', verbose_name='Detalle Transferencia')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Reporte de Pago',
                'verbose_name_plural': 'Reportes de Pagos',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='RegistroValidacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('VERIFICADO', '✅ Verificado correcto'), ('RECHAZADO', '❌ Rechazado'), ('APLICADO', '📄 Aplicado a contrato'), ('CREAR_CONTRATO', '🆕 Crear contrato (externo → interno)'), ('NOTA_INTERNA', '📝 Nota interna')], max_length=20, verbose_name='Acción')),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de validación')),
                ('nota_interna', models.TextField(blank=True, max_length=500, null=True, verbose_name='Nota interna')),
                ('contrato_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_pago', to='myapp.contratocliente', verbose_name='Contrato creado (cliente externo migrado)')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='myapp.reportepago', verbose_name='Reporte de pago')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Registro de Validación',
                'verbose_name_plural': 'Registros de Validaciones',
                'ordering': ['-fecha_validacion'],
            },
        ),
        migrations.AddIndex(
            model_name='reportepago',
            index=models.Index(fields=['contrato'], name='myapp_repor_contrat_ba2c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepago',
            index=models.Index(fields=['cliente_externo'], name='myapp_repor_cliente_7b4f45_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepago',
            index=models.Index(fields=['estado'], name='myapp_repor_estado_faebf0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepago',
            index=models.Index(fields=['fecha_reporte'], name='myapp_repor_fecha_r_0a53a9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepago',
            index=models.Index(fields=['medio_pago'], name='myapp_repor_medio_p_ee44d1_idx'),
        ),
        migrations.AddIndex(
            model_name='reportepago',
            index=models.Index(fields=['tipo_cliente'], name='myapp_repor_tipo_cl_67be0a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovalidacionpago',
            index=models.Index(fields=['reporte'], name='myapp_regis_reporte_0c5404_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovalidacionpago',
            index=models.Index(fields=['fecha_validacion'], name='myapp_regis_fecha_v_a13761_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovalidacionpago',
            index=models.Index(fields=['accion'], name='myapp_regis_accion_4850ff_idx'),
        ),
    ]
