# Generated by Django 4.2.29 on 2026-05-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_cargar_bancos_venezuela'),
    ]

    operations = [
    ]
