# Generated by Django 4.2.29 on 2026-05-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_agregar_bancos'),
    ]

    operations = [
    ]
