# Generated by Django 4.2.29 on 2026-05-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_cargar_bancos_venezuela'),
        ('myapp', '0044_cargar_bancos_venezuela'),
    ]

    operations = [
    ]
