# Generated by Django 4.2.29 on 2026-05-13 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0045_merge_20260512_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoporteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('INTERNO', 'Cliente con contrato'), ('EXTERNO', 'Cliente externo')], max_length=10, verbose_name='Tipo de cliente')),
                ('reclamo', models.TextField(max_length=1000, verbose_name='Reclamo')),
                ('observacion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='soportes_clientes/%Y/%m/', verbose_name='Foto')),
                ('estado', models.CharField(choices=[('NO_LEIDO', 'No leído'), ('LEIDO', 'Leído')], db_index=True, default='NO_LEIDO', max_length=20, verbose_name='Estado')),
                ('fecha_leido', models.DateTimeField(blank=True, help_text='Fecha y hora en que el soporte fue leído por primera vez por el personal', null=True, verbose_name='Fecha de lectura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soportes_cliente', to='myapp.clienteexterno', verbose_name='Cliente externo')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soportes_cliente', to='myapp.contratocliente', verbose_name='Contrato del cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_cliente_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Soporte a Cliente',
                'verbose_name_plural': 'Soportes a Clientes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='myapp_sopor_estado_bf069c_idx'), models.Index(fields=['fecha_leido'], name='myapp_sopor_fecha_l_c2f4fb_idx'), models.Index(fields=['fecha_creacion'], name='myapp_sopor_fecha_c_4b24f1_idx')],
            },
        ),
    ]
