# Generated by Django 4.2.29 on 2026-05-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_soportecliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepagomovil',
            name='banco_receptor',
        ),
        migrations.RemoveField(
            model_name='detallepagomovil',
            name='cedula_titular',
        ),
        migrations.RemoveField(
            model_name='detallepagomovil',
            name='referencia',
        ),
    ]
