# Generated by Django 4.2.29 on 2026-05-14 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0047_remove_detallepagomovil_banco_receptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInteresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('mensaje', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('NUEVO', '🆕 Nuevo (sin contacto)'), ('CONTACTADO', '📞 Contactado'), ('EN_SEGUIMIENTO', '⏳ En seguimiento'), ('CONVERTIDO', '✅ Convertido a cliente'), ('PERDIDO', '❌ Perdido/No interesado')], db_index=True, default='NUEVO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_contactado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contacto')),
                ('notas_seguimiento', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas de seguimiento')),
                ('cliente_potencial_convertido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origen', to='myapp.clientepotencial', verbose_name='Cliente potencial convertido')),
                ('contactado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_contactados', to=settings.AUTH_USER_MODEL, verbose_name='Contactado por')),
            ],
            options={
                'verbose_name': 'Lead Interesado (Web)',
                'verbose_name_plural': 'Leads Interesados (Web)',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='myapp_leadi_estado_0e1fbb_idx'), models.Index(fields=['fecha_creacion'], name='myapp_leadi_fecha_c_173bf0_idx'), models.Index(fields=['telefono'], name='myapp_leadi_telefon_a49258_idx')],
            },
        ),
    ]
