# Generated by Django 4.2.29 on 2026-05-15 23:07

from django.db import migrations, models


def set_default_latitud_longitud(apps, schema_editor):
    """Establece 0 como valor por defecto para latitud y longitud en contratos existentes"""
    ContratoCliente = apps.get_model('myapp', 'ContratoCliente')
    
    # Actualizar todos los contratos que tengan latitud o longitud NULL a 0
    ContratoCliente.objects.filter(latitud__isnull=True).update(latitud=0.0)
    ContratoCliente.objects.filter(longitud__isnull=True).update(longitud=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_leadinteresado'),
    ]

    operations = [
        # 1. Agregar campo cashea con default=False
        migrations.AddField(
            model_name='contratocliente',
            name='cashea',
            field=models.BooleanField(default=False, verbose_name='Cashea'),
        ),
        
        # 2. Agregar campo latitud (permitiendo nulos temporalmente)
        migrations.AddField(
            model_name='contratocliente',
            name='latitud',
            field=models.FloatField(
                blank=True,
                help_text='Coordenada de la ubicación del cliente',
                null=True,
                verbose_name='Latitud'
            ),
        ),
        
        # 3. Agregar campo longitud (permitiendo nulos temporalmente)
        migrations.AddField(
            model_name='contratocliente',
            name='longitud',
            field=models.FloatField(
                blank=True,
                help_text='Coordenada de la ubicación del cliente',
                null=True,
                verbose_name='Longitud'
            ),
        ),
        
        # 4. Ejecutar función para establecer 0 en registros existentes
        migrations.RunPython(set_default_latitud_longitud, reverse_code=migrations.RunPython.noop),
        
        # 5. Modificar latitud para que no permita nulos y tenga default=0
        migrations.AlterField(
            model_name='contratocliente',
            name='latitud',
            field=models.FloatField(default=0.0, verbose_name='Latitud'),
        ),
        
        # 6. Modificar longitud para que no permita nulos y tenga default=0
        migrations.AlterField(
            model_name='contratocliente',
            name='longitud',
            field=models.FloatField(default=0.0, verbose_name='Longitud'),
        ),
        
        # 7. Modificar el campo estado (tu cambio existente)
        migrations.AlterField(
            model_name='contratocliente',
            name='estado',
            field=models.CharField(
                choices=[
                    ('EN_PROCESO', 'En Proceso'),
                    ('COMPLETADO', 'Completado'),
                    ('NO_COMPLETADO', 'No Completado'),
                    ('RENUNCIADO', 'Renunciado')
                ],
                default='EN_PROCESO',
                max_length=15,
                verbose_name='Estado del Contrato'
            ),
        ),
    ]