# Generated by Django 4.2.29 on 2026-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_contratocliente_cashea_contratocliente_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocliente',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contratocliente',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Coordenada de la ubicación del cliente', null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='contratocliente',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Coordenada de la ubicación del cliente', null=True, verbose_name='Longitud'),
        ),
    ]
