# Generated by Django 4.2.29 on 2026-05-19 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0050_alter_contratocliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', '⏳ Pendiente'), ('CONTACTADO', '✅ Contactado'), ('NO_RESPONDE', '❌ No Responde')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado de la llamada')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Notas de la llamada')),
                ('fecha_llamada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de la llamada')),
                ('cliente_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='myapp.clienteexterno')),
                ('cliente_potencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='myapp.clientepotencial')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='myapp.contratocliente')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Registro de Llamada',
                'verbose_name_plural': 'Registros de Llamadas',
                'ordering': ['-fecha_llamada'],
                'indexes': [models.Index(fields=['estado'], name='myapp_regis_estado_5636b5_idx'), models.Index(fields=['fecha_llamada'], name='myapp_regis_fecha_l_371e92_idx')],
            },
        ),
    ]
