# Generated by Django 4.2.29 on 2026-05-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_instalacion_fecha_creacion_registrollamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocliente',
            name='cashea',
            field=models.BooleanField(default=False, verbose_name='Cashea o pago de modem completo'),
        ),
    ]
