# Generated by Django 4.2.29 on 2026-06-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_alter_contratocliente_cashea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportepago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobante/', verbose_name='Comprobante de pago'),
        ),
    ]
