# Generated by Django 4.2.29 on 2026-06-05 16:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_reportepago_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportepago',
            name='comprobante',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Comprobante de pago'),
        ),
    ]
